### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by ensonic**
Does not fix it fully.
See #11

### CODE REVIEW

**Comment by ensonic** [comment]
@jonneva for the travis setup, you would need to go though
https://docs.travis-ci.com/user/getting-started/, steps 1/2. If you would be willing to add me as a collaborator on the project I can take care of it. The CI might not immediately work, usually the .travis.yml needs a bit of finetuning, lets see :)

**Comment by pokitto** [comment]
Thanks for the Travis CI tip, was not familiar with it.

**Comment by ensonic** [comment]
Unfortunately I still can't create the project there. I guess I would need to become and member of the 'pokitto' org and not just the sim project. Sorry for the hassle, I set this up fro a few project already, but some are my own (full admin) and for others I seems to have wider access too.

**Comment by pokitto** [comment]
How about outlining here whats involved in the setup and I will take care of it ?

**Comment by ensonic** [comment]
@jonneva: https://docs.travis-ci.com/user/getting-started/ steps 1,2:

1.) Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation.
2.) Once you’re signed in, and we’ve synchronized your GitHub repositories, go to your profile page and enable Travis CI for the open source repository you want to build.

**Comment by ensonic** [comment]
Ping. Please let me know if there are any questions wrt travis-ci (https://travis-ci.org/pokitto/PokittoSim) . Also on the open pull request. If you don't mind I merge them, okay?

**Comment by haviital** [comment]
Looks ok for me

**Pull request merged**
