### PR TITLE
Invisible color direct mode

### PR DESCRIPTION
**Pull request by HomineLudens**
Just a propose to add invisible color in direct mode.
Not sure if it's the best way to do this.

### CODE REVIEW

**Comment by pokitto** [comment]
Hmm. The point of directPixel et al. is they do not use a palette. 

Please modify this as follows:
- add new color property directinvisiblecolor in addition to directcolor and directbgcolor. just "invisiblecolor" could be misleading
- directinvisiblecolor should be an uint16_t (RGB565 value) like directcolor and directbgcolor

**Comment by HomineLudens** [comment]
Easy fix, but how disable transparent color? Do you like 0xF0FF fucsia?
Also found this that sound strange in Display::directChar

https://github.com/pokitto/PokittoSim/blob/93336e7b9e6e72e2d2757e80d4288d721bed299d/POKITTO_CORE/PokittoDisplay.cpp#L315

**Comment by pokitto** [comment]
I am sorry @Effer . Your original idea was correct. Its less confusing to have 1 transparent color that is part of the palette. If possible, please revert back to the previous commit and I will merge. Sorry for making you run around in circles.

**Comment by pokitto** [comment]
Aha! now I know how this works! I will just pull this in and discard the other one! Thanks Filippo

**Comment by HomineLudens** [comment]
Hi Jonne,
really no problem to revert if you prefer the other approach but I see you take the **directinvisiblecolor**  way.  I've open the pull request to discuss about this and your comments are welcome.

I know it's a lot of refactoring, but maybe a naming convention to distinct the 565 colors from palette index could help lots of people to avoid some errors.

Also what about the code mentioned above, in directChar?
Could we remove that? Direct pixel now take care of transparent color and avoid draw pixel with color==invisible color index, has little sense to me.

**Comment by pokitto** [comment]
Hi Filippo. I tried to merge the previous commit, and it still merged the **directinvisible** version
- that was not what I intended -
i think the previous version you did was correct (**invisiblecolor**) and that is the one I wanted to merge. But my git-skills are not so good.

i have reverted back to before the directinvisiblecolor. Please make a new pull request.

**Pull request merged**
